services:
  frontend:
    image: ghcr.io/alex-sviridov/readtrail/frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
  backend:
    image: ghcr.io/alex-sviridov/readtrail/backend
    volumes:
      - ./backend/pb_data:/pb/pb_data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./webproxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./webproxy/ssl/cert.pem:/etc/nginx/ssl/cert.pem:ro
      - ./webproxy/ssl/key.pem:/etc/nginx/ssl/key.pem:ro
    depends_on:
      - frontend
      - backend